### ISSUE TITLE
Add docker so that plugins get automatically installed

### ISSUE THREAD

**Issue by marcingrzejszczak** [kamilszymanski/jobdsl-confitura-talk#1]
Check this out 
- https://github.com/spring-cloud/spring-cloud-jenkins-dsl/blob/master/docker-compose.yml
- https://github.com/spring-cloud/spring-cloud-jenkins-dsl/blob/master/Dockerfile
- https://github.com/spring-cloud/spring-cloud-jenkins-dsl/blob/master/plugins.txt

**Comment by kamilszymanski** [comment]
Hi Marcin,
thanks for the issue, you're absolutely right that having to install required plugins manually through Jenkins UI is not the most exciting thing to do.
I've added a script that allows to automatically install required plugins, however it's still required to execute this step manually.
The reason for this is that I want users to grasp the whole picture of using Job DSL instead of having some pieces autoconfigured behind the scenes.
